### ISSUE TITLE
Talismans not fully Loading on Server join

### ISSUE THREAD

**Issue by Miryex** [Auxilor/Talismans#12]
When joining my Server, not all Talismans seem to load. They do load after the first restart but after rejoining once, I have to 
manually reselect them in my inventory.

1. Use my Config I guess
2. Give yourself a vibrance talisman (as that talisman doesnt work and some others like defense and strengh talisman which only works with ecoskills)
3. Join Server, (They should be working)
4. Rejoin (shouldnt be working anymore)
5. Reselect them in inventory or drop and pick them up (should be working again)

**Expected behavior**
Instantly load all talismans without having to reselect some on serverjoin

**Server Information (please complete the following information):**
- Version: Paper version git-Paper-205 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 36a1650)
- Version of plugin and eco: eco-6.25.2-all, Ta
lismans v5.25.5, EcoSkills v1.20.22

Config as .txt file because I couldnt it add as YML:
[talismans.txt](https://github.com/Auxilor/Talismans/files/8104587/talismans.txt)

**Comment by WillFP** [comment]
Should be fixed in latest

**Comment by Miryex** [comment]
Not fixed for me :/

**Comment by Miryex** [comment]
Do I have to make a new Bug report or will this get adressed?

**Comment by Miryex** [comment]
Uh
