### ISSUE TITLE
Talismans - Error with Kingdoms

### ISSUE THREAD

**Issue by Aides123** [Auxilor/Talismans#15]
**Describe the bug**
After uploading talismans, a bunch of errors appear in the console.
Talismans have only been uploaded and no player has them yet.

Kingdoms ver: Kingdom: 1.12.2.0.0.1-BETA
https://www.spigotmc.org/resources/kingdomsx.77670/

**To Reproduce**
Just upload talismans to the server with kingdoms plugin
https://pastebin.com/NSUaGddi

**Server Information (please complete the following information):**
- This server is running Pufferfish version git-Pufferfish-47 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a786526 on HEAD)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
![image](https://user-images.githubusercontent.com/23367220/156564211-f3f8875b-6b9b-4759-a62f-9a7d3fc49b92.png)

**Comment by Aides123** [comment]
@WillFP Could you please check this out as it is very important to me :/

**Comment by WillFP** [comment]
Update eco

**Comment by Aides123** [comment]
> Update eco

Check https://github.com/Auxilor/eco/issues/104
