### ISSUE TITLE
Kicking from the server when 50+ talismans are created

### ISSUE THREAD

**Issue by nikto0001** [Auxilor/Talismans#16]
After creating approximately more than 50 talismans, it is not possible to connect to the server.
Messages in the console:
Lost connection: internal exception: 
lost connection: internal Exception: net.minecraft.network.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutRecipeUpdate is 2218477. Max is 2097152

**Server Information**
- Version: 1.18.1 Purpur-1566
- Version of plugin and eco: Eco: 6.27.0, talismans: 5.28.1

**Comment by PrimalPower** [comment]
Thats not because of talismans. Its because too much recipe lore. It is a problem more with eco than talismans. I'm first to have this issue and it is frustration. This error is the limit to everything

**Comment by WillFP** [comment]
There's an option in eco config.yml to get around (not fix) this bug, but it breaks the recipe book playing nicely. If you have a custom recipe GUI it's not a problem
