### ISSUE TITLE
Add custommodeldata to Talismans

### ISSUE THREAD

**Issue by Xiao-MoMi** [Auxilor/Talismans#19]
Many servers use texture pack and custommodeldata plays an important role. I can't find out how to use it in wiki so I guess this option is not available.
This might be applied to your other plugins.  :D

**Comment by Sedri05** [comment]
already a thing `item: material custom-model-data:number`

if only you looked at the wiki https://plugins.auxilor.io/all-plugins/the-item-lookup-system
