### ISSUE TITLE
[BUG] [CONFIGURATION] Missing cooldown message in the plugin configuration of lang.yml.

### ISSUE THREAD

**Issue by Futodama** [Auxilor/Talismans#23]
**Describe the bug**
If I wanted to translate the lines from the plugin responsible for displaying the inscription about the recharge of the talisman, I came across the problem of the complete absence of this line in the lang.yml file. I also didn't find this line in the plugin file on github.

**Screenshots**
![image](https://user-images.githubusercontent.com/73364285/160284337-18f03ecc-7b67-4c8f-b42a-67e4513b29b3.png)
![image](https://user-images.githubusercontent.com/73364285/160284346-9441424b-1ee8-4532-8be2-eb468721fd32.png)
![image](https://user-images.githubusercontent.com/73364285/160284351-96af04aa-62e8-4fb7-b94e-a0f4f615e2ee.png)

**Server Information (please complete the following information):**
- Version: git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
- Version: eco v6.30.2 and Talismans v5.36.0

**Additional context**
See ticket: https://discord.com/channels/452518336627081236/957340104626692137

**Comment by iSeitan** [comment]
I took time to take a look at this in the tickets on discord, and I imagine that the /talismans reload don’t sparse the message correctly, probably an easy fix but Aux will need to take a look at it himself

**Comment by WillFP** [comment]
Fixed in latest
