### ISSUE TITLE
Damage Filters are not working

### ISSUE THREAD

**Issue by Miryex** [Auxilor/Talismans#32]
**Describe the bug**
Damage Filters are not working.

**To Reproduce**
1. Give yourself necrosis Talisman
2. Try to take damage

**Server Information (please complete the following information):**
- Version: git-Purpur-1778 (MC: 1.19.2)*
- Version: eco 6.41.1, Talismans 5.110.0

**Comment by DimaSergeew** [comment]
> **Describe the bug** Damage Filters are not working.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Give yourself necrosis Talisman
> 2. Try to take damage
> 
> **Server Information (please complete the following information):**
> 
> * Version: git-Purpur-1778 (MC: 1.19.2)*
> * Version: eco 6.41.1, Talismans 5.110.0

I already found this bug it also works with immunity now I will publish a detailed report

**Comment by DimaSergeew** [comment]
> > 
> 
> Yeah ofc its with Immunity too. The necrosis Talisman is just an example. The problem is as Ive described that damage filters are not working which means that ANY kind of damage including poison (Immunity Talisman) dont work.

I have been trying to explain to them for 7 days that they have this bug, but they said that my configuration is not correct -__- see my bug ticket above, I described everything in detail there! to fix the bug, install Talismans v5.102.3 for now

**Comment by devbaraus** [comment]
Doesn't work aswell :disappointed: 

```
  - id: damage_multiplier
    args:
      multiplier: 0
    filters:
      projectiles: 
        - arrow
    triggers:
      - take_damage
```

**Comment by 0ft3n** [comment]
Fixed in https://github.com/Auxilor/Talismans/pull/35
