### ISSUE TITLE
Bug 2 types of talisman cause complete immortality in players!

### ISSUE THREAD

**Issue by DimaSergeew** [Auxilor/Talismans#33]
**Describe the bug**
The error is related to the fact that the player, having the talisman "Necrosis" or "immunity", then he becomes immortal

**To Reproduce**
1. Go to 'Install any version of the plugin not lower than talismans v 5.103.0, and take the "Necrosis" or "immunity" talisman in your hand, congratulations, you are immortal'

**Expected behavior**
no bugs

**Server Information (please complete the following information):**
- Version: Mirai 1.19.2-R0.1-SNAPSHOT
- Version of plugin and eco (`eco-6.41.1-all`, `Talismans 5.112.0`)

**Additional context**
I decided to carefully find after which version this bug happened, I noticed that in version 5.102.3 everything works fine and there is no bug, but if I install the version of the Talismans plugin v5.103.0 and higher, then there is a bug and it is not corrected!
Which says that the bug appeared in version 5.103.0, I think this will make it easier for you to find it

Here is a video of the bug: https://youtu.be/lbaPmnX19aU

**Comment by 0ft3n** [comment]
Fixed in https://github.com/Auxilor/Talismans/pull/35
